#!/usr/bin/env python3
"""Add new photographs to the site.

Usage:
    python3 tools/add_photos.py
        Process everything in photos-to-add/<category>/ and delete the
        originals once they are on the site. This is what the GitHub Action
        runs after every push.

    python3 tools/add_photos.py CATEGORY PHOTO [PHOTO ...] [--alt "description"]
        Add specific files to one category.

Categories: weddings, couples, family, kids, portraits, events, travel

For each photo this writes the three WebP renditions the site uses
(thumb 900px, full 1600px, xl 2400px on the long edge) and appends an
entry to assets/js/photos.js. New photos appear at the end of the portfolio.
Requires Pillow (pip3 install pillow); pillow-heif adds iPhone HEIC support.
"""
import argparse
import json
import re
import sys
from pathlib import Path

from PIL import Image, ImageOps

try:
    from pillow_heif import register_heif_opener
    register_heif_opener()
except ImportError:
    pass

ROOT = Path(__file__).resolve().parent.parent
IMG = ROOT / "assets" / "img"
INBOX = ROOT / "photos-to-add"
PHOTOS_JS = ROOT / "assets" / "js" / "photos.js"
CATEGORIES = ["weddings", "couples", "family", "kids", "portraits", "events", "travel"]
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff", ".heic", ".heif"}
SIZES = {"thumb": 900, "full": 1600, "xl": 2400}
HEADER = "/* Generated by tools/add_photos.py - do not edit by hand. */\n"


def load_photos():
    text = PHOTOS_JS.read_text()
    match = re.search(r"window\.YC_PHOTOS\s*=\s*(\[.*\]);", text, re.S)
    if not match:
        sys.exit("Could not read assets/js/photos.js")
    return json.loads(match.group(1))


def save_photos(photos):
    body = json.dumps(photos, separators=(",", ":"), ensure_ascii=False)
    PHOTOS_JS.write_text(HEADER + "window.YC_PHOTOS = " + body + ";\n")


def resized(img, long_edge):
    w, h = img.size
    scale = min(1.0, long_edge / max(w, h))
    if scale == 1.0:
        return img
    return img.resize((round(w * scale), round(h * scale)), Image.LANCZOS)


def average_colour(img):
    r, g, b = img.resize((1, 1), Image.LANCZOS).getpixel((0, 0))[:3]
    return "#%02x%02x%02x" % (r, g, b)


def add_photo(photos, src, category, alt=None):
    img = ImageOps.exif_transpose(Image.open(src)).convert("RGB")
    pid = "yc-%03d" % (max(int(p["id"].split("-")[1]) for p in photos) + 1)

    for folder, edge in SIZES.items():
        resized(img, edge).save(IMG / folder / (pid + ".webp"), "WEBP", quality=82, method=6)

    largest = resized(img, SIZES["xl"])
    alt = alt or re.sub(r"[_\-]+", " ", src.stem).strip()
    photos.append({
        "id": pid,
        "w": largest.width,
        "h": largest.height,
        "cat": category,
        "alt": alt,
        "c": average_colour(img),
    })
    print("added %s  <- %s  (%s, \"%s\")" % (pid, src.name, category, alt))


def process_inbox(photos):
    added = 0
    for category in CATEGORIES:
        folder = INBOX / category
        if not folder.is_dir():
            continue
        for src in sorted(folder.iterdir()):
            if src.suffix.lower() not in EXTENSIONS:
                continue
            add_photo(photos, src, category)
            src.unlink()
            added += 1
    return added


def main():
    parser = argparse.ArgumentParser(description="Add photos to the portfolio.")
    parser.add_argument("category", nargs="?", choices=CATEGORIES)
    parser.add_argument("photos", nargs="*", type=Path)
    parser.add_argument("--alt", help="short description (used for every photo given)")
    args = parser.parse_args()

    photos = load_photos()

    if args.category is None:
        if not process_inbox(photos):
            print("No new photos in photos-to-add/")
            return
    else:
        if not args.photos:
            parser.error("give at least one photo after the category")
        for src in args.photos:
            if not src.is_file():
                sys.exit("Not found: %s" % src)
            add_photo(photos, src, args.category, args.alt)

    save_photos(photos)


if __name__ == "__main__":
    main()
