#!/usr/bin/env python3
"""Add new photographs to the site.

Usage:
    python3 tools/add_photos.py
        Process everything sitting in photos-to-add/<category>/ — including
        whole folders dropped in, however deeply nested. This is what the
        GitHub Action runs after every push (with --clean).

    python3 tools/add_photos.py CATEGORY PHOTO [PHOTO ...] [--alt "description"]
        Add specific files to one category.

    --clean   delete the originals from photos-to-add/ once they are on the
              site. The Action uses this; locally the originals are left alone
              so a dropped-in file is never the copy you lose.

Categories: weddings, housewarming, events, portraits

For each photo this writes the three WebP renditions the site uses
(thumb 900px, full 1600px, xl 2400px on the long edge) and appends an entry
to assets/js/photos.js. The portfolio arranges them on its own — no layout
work, no HTML to edit. Photos already on the site are recognised and skipped,
so re-running is safe.

Requires Pillow (pip3 install pillow); pillow-heif adds iPhone HEIC support.
"""
import argparse
import hashlib
import json
import os
import re
import sys
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

from PIL import Image, ImageOps

from stamp_assets import stamp

try:
    from pillow_heif import register_heif_opener
    register_heif_opener()
except ImportError:
    pass

ROOT = Path(__file__).resolve().parent.parent
IMG = ROOT / "assets" / "img"
INBOX = ROOT / "photos-to-add"
PHOTOS_JS = ROOT / "assets" / "js" / "photos.js"

CATEGORIES = ["weddings", "housewarming", "events", "portraits"]
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff", ".heic", ".heif"}
# Raw files are left where they are: the site can't use them and they would
# bloat the repository for ever if they were committed.
RAW_EXTENSIONS = {".cr2", ".cr3", ".nef", ".arw", ".raf", ".rw2", ".orf",
                  ".dng", ".srw", ".pef", ".x3f"}
# Lightroom catalogues and their preview pyramids hold thousands of stray
# jpegs that are not photographs anyone chose.
SKIP_DIR_SUFFIXES = (".lrdata", ".lrcat-data", ".lrcat", ".photoslibrary")

SIZES = {"thumb": 900, "full": 1600, "xl": 2400}
HEADER = "/* Generated by tools/add_photos.py - do not edit by hand. */\n"

# Filenames like YOG02441, IMG_1234 or the UUID a download service hands you
# describe nothing, so they must not become the caption under the photograph.
CAMERA_NAME = re.compile(r"^(?:img|dsc|dscf|dscn|pict|p|yog|mvi|gopr|photo)?[ _-]?\d{2,6}$", re.I)
UUID_NAME = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$|^[0-9a-f]{16,}$", re.I)
# A real description has at least one pronounceable word in it.
WORD = re.compile(r"[A-Za-z]{3,}")
GENERIC_ALT = {
    "weddings": "Wedding photograph by YC Photography",
    "housewarming": "Housewarming photograph by YC Photography",
    "events": "Event photograph by YC Photography",
    "portraits": "Portrait by YC Photography",
}


def load_photos():
    text = PHOTOS_JS.read_text()
    match = re.search(r"window\.YC_PHOTOS\s*=\s*(\[.*\]);", text, re.S)
    if not match:
        sys.exit("Could not read assets/js/photos.js")
    return json.loads(match.group(1))


def save_photos(photos):
    body = json.dumps(photos, separators=(",", ":"), ensure_ascii=False)
    PHOTOS_JS.write_text(HEADER + "window.YC_PHOTOS = " + body + ";\n")
    stamp()                                       # so browsers fetch the new list


def fingerprint(path):
    """Identify a photo by its size and its first and last 256KB.

    Enough to recognise a file that has already been added without reading
    gigabytes back off the disk on every run.
    """
    size = path.stat().st_size
    h = hashlib.sha1(str(size).encode())
    with path.open("rb") as f:
        h.update(f.read(262144))
        if size > 524288:
            f.seek(-262144, os.SEEK_END)
            h.update(f.read(262144))
    return h.hexdigest()[:12]


def describe(path, category):
    """Turn a filename into a caption, or fall back to a plain description."""
    stem = re.sub(r"[_\-]+", " ", path.stem).strip()
    words = [w for w in WORD.findall(stem) if re.search(r"[aeiou]", w, re.I)]
    if not stem or CAMERA_NAME.match(path.stem) or UUID_NAME.match(path.stem) or not words:
        return GENERIC_ALT[category], True
    return stem, False


def resized(img, long_edge):
    w, h = img.size
    scale = min(1.0, long_edge / max(w, h))
    if scale == 1.0:
        return img
    return img.resize((round(w * scale), round(h * scale)), Image.LANCZOS)


def render(job):
    """Write the three renditions for one photo. Runs in a worker process."""
    src, pid = job
    try:
        img = ImageOps.exif_transpose(Image.open(src)).convert("RGB")
        for folder, edge in SIZES.items():
            resized(img, edge).save(IMG / folder / (pid + ".webp"), "WEBP",
                                    quality=82, method=6)
        largest = resized(img, SIZES["xl"])
        r, g, b = img.resize((1, 1), Image.LANCZOS).getpixel((0, 0))[:3]
        return pid, largest.width, largest.height, "#%02x%02x%02x" % (r, g, b), None
    except Exception as err:                      # a corrupt file must not stop the run
        for folder in SIZES:                      # leave no half-written renditions behind
            (IMG / folder / (pid + ".webp")).unlink(missing_ok=True)
        return pid, 0, 0, "", str(err)


def walk(folder):
    """Every usable photo under a category folder, however it was dropped in."""
    found, raw = [], 0
    for base, dirs, files in os.walk(folder):
        dirs[:] = sorted(d for d in dirs
                         if not d.startswith(".")
                         and not d.lower().endswith(SKIP_DIR_SUFFIXES))
        for name in sorted(files):
            if name.startswith("."):              # .DS_Store, ._AppleDouble
                continue
            path = Path(base) / name
            suffix = path.suffix.lower()
            if suffix in EXTENSIONS:
                found.append(path)
            elif suffix in RAW_EXTENSIONS:
                raw += 1
    return found, raw


def prune(folder):
    """Remove the folders left empty once their photos are on the site."""
    for base, dirs, files in os.walk(folder, topdown=False):
        here = Path(base)
        if here == folder:
            continue
        if not any(p.name != ".DS_Store" for p in here.iterdir()):
            for junk in here.iterdir():
                junk.unlink()
            here.rmdir()


def collect(photos):
    """Pair every new photo in the inbox with the category folder it sits in."""
    known = {p["k"] for p in photos if "k" in p}
    jobs, dupes, raw_total = [], [], 0
    loose = [p for p in INBOX.iterdir()
             if p.is_file() and p.suffix.lower() in EXTENSIONS | RAW_EXTENSIONS]

    for category in CATEGORIES:
        folder = INBOX / category
        if not folder.is_dir():
            continue
        found, raw = walk(folder)
        raw_total += raw
        for src in found:
            key = fingerprint(src)
            if key in known:
                dupes.append(src)
                continue
            known.add(key)
            jobs.append((src, category, key))

    if loose:
        print("! %d photo(s) sit loose in photos-to-add/ and were left alone."
              % len(loose))
        print("  Move them into one of: %s" % ", ".join(CATEGORIES))
    if raw_total:
        print("! %d raw file(s) skipped — the site uses JPEG, PNG, WebP, TIFF "
              "or HEIC." % raw_total)
    if dupes:
        print("- %d photo(s) already on the site, skipped." % len(dupes))
    return jobs, dupes


def add(photos, jobs, clean, alt_override=None):
    """Render every new photo in parallel and record it in photos.js."""
    start = max((int(p["id"].split("-")[1]) for p in photos), default=0) + 1
    queue, meta = [], []
    for offset, (src, category, key) in enumerate(jobs):
        pid = "yc-%03d" % (start + offset)
        if alt_override:
            alt, auto = alt_override, False
        else:
            alt, auto = describe(src, category)
        queue.append((str(src), pid))
        meta.append((src, category, key, alt, auto))

    print("Processing %d photo(s)…" % len(queue))
    workers = min(os.cpu_count() or 2, 8)
    added, failed = 0, 0
    with ProcessPoolExecutor(max_workers=workers) as pool:
        for (pid, w, h, colour, err), (src, category, key, alt, auto) in zip(
                pool.map(render, queue, chunksize=1), meta):
            if err:
                print("  x %s — %s" % (src.name, err))
                failed += 1
                continue
            entry = {"id": pid, "w": w, "h": h, "cat": category, "alt": alt,
                     "c": colour, "k": key}
            if auto:
                entry["auto"] = 1
            photos.append(entry)
            added += 1
            print("  %s  <- %s  (%s)" % (pid, src.name, category))
            if clean:
                src.unlink()

    return added, failed


def tidy(dupes):
    """Clear out photos that are already on the site, and the empty folders."""
    for src in dupes:
        src.unlink()
    for category in CATEGORIES:
        folder = INBOX / category
        if folder.is_dir():
            prune(folder)


def main():
    parser = argparse.ArgumentParser(description="Add photos to the portfolio.")
    parser.add_argument("category", nargs="?", choices=CATEGORIES)
    parser.add_argument("photos", nargs="*", type=Path)
    parser.add_argument("--alt", help="short description (used for every photo given)")
    parser.add_argument("--clean", action="store_true",
                        help="delete the originals from photos-to-add/ afterwards")
    args = parser.parse_args()

    photos = load_photos()

    dupes = []
    if args.category is None:
        jobs, dupes = collect(photos)
        if not jobs:
            print("No new photos in photos-to-add/")
            if args.clean:
                tidy(dupes)
            return
    else:
        if not args.photos:
            parser.error("give at least one photo after the category")
        jobs = []
        for src in args.photos:
            if not src.is_file():
                sys.exit("Not found: %s" % src)
            jobs.append((src, args.category, fingerprint(src)))

    added, failed = add(photos, jobs, args.clean, args.alt)
    if args.clean:
        tidy(dupes)

    if added:
        save_photos(photos)
        print("\n%d photo(s) added. The portfolio arranges them on its own." % added)
        if not args.clean:
            print("Originals left in photos-to-add/ — they are removed once the "
                  "photos are live.")
    if failed:
        print("%d photo(s) could not be read and were left in place." % failed)


if __name__ == "__main__":
    main()
